### ISSUE TITLE
[BUG]Problema nos arquivos estáticos  do micro serviços de comentários

### ISSUE THREAD

**Issue by Lcunha** [fga-eps-mds/2018.2-Roles#107]
**Describe the bug**
Heroku não consegue instalar o collectstatic do django rest por falta de configuração no setting.py sobre arquivos estáticos.

**Expected behavior**
Instalação das dependências de projeto. [Pip]
 
**Erro**
```
python comments_microservice/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "comments_microservice/manage.py", line 15, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 189, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
           handler(path, prefixed_path, storage)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 344, in copy_file
           if not self.delete_file(path, prefixed_path, source_storage):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 250, in delete_file
           if self.storage.exists(prefixed_path):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 308, in exists
           return os.path.exists(self.path(name))
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 43, in path
           raise ImproperlyConfigured("You're using the staticfiles app "
       django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
 !     Error while running '$ python comments_microservice/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
```

**Comment by Lcunha** [comment]
@Lcunha Henrique
